package pakanternak;
import static pakanternak.koneksi.buatkoneks;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author I Kadek Artha Wiguna
 * tgl:2024-06-27
 */ 
public class Jform extends javax.swing.JFrame {
        DefaultTableModel TM = new DefaultTableModel();

    public Jform() throws SQLException {
        initComponents();
        tblPakan.setModel(TM);
        TM.addColumn("ID_Pakan");
        TM.addColumn("Nama_Pakan");
        TM.addColumn("Berat_Pakan");
        TM.addColumn("Jenis_Pakan");
        TM.addColumn("Harga_Pakan");
        TM.addColumn("Stok_Pakan");
        
        this.setTitle("Aplikasi Pakan Ternak");
        ImageIcon IC = new ImageIcon ("img/logo.png");
        this.setIconImage(IC.getImage());
        
        List_All();
        kosongkanform();
        loadphoto("");
    }
        private void loadphoto(String idx){
        String nopic= "src/img/logo.png";
        String ph = "src/img/"+idx+".png";
        BufferedImage photoPakan = loadIMG.loadImage(ph);
        if(photoPakan == null){
            photoPakan = loadIMG.loadImage(nopic);
            
        }
        ImageIcon iconphoto = new ImageIcon(photoPakan);
        Foto.setIcon(iconphoto);
        }
    
    private void List_All() throws SQLException{
        TM.getDataVector().removeAllElements();
        TM.fireTableDataChanged();
        
        Connection cnn = buatkoneks();
        if( !cnn.isClosed() ){
            String sql = "SELECT * FROM pakan_ternak;";
            PreparedStatement PS = cnn.prepareStatement(sql);
            ResultSet rs = PS.executeQuery();
            while( rs.next() ){
                Object[] dta = new Object[6];
                dta[0] = rs.getInt("ID_Pakan");
                dta[1] = rs.getString("Nama_Pakan");
                dta[2] = rs.getString("Berat_Pakan");
                dta[3] = rs.getString("Jenis_Pakan");
                dta[4] = rs.getString("Harga_Pakan");
                dta[5] = rs.getString("Stok_Pakan");
                TM.addRow(dta);
            }
        }
        
    }
    
private void StoreData() throws SQLException {
    Connection cnn = buatkoneks();
        String ID = txtID.getText();
        String NM = txtNama.getText();
        String BT = txtBerat.getText();
        String JS = txtJenis.getText();
        String HG = txtHarga.getText();
        String ST = txtStok.getText();
         if(!cnn.isClosed() ){
             PreparedStatement PS = cnn.prepareStatement("INSERT INTO pakan_ternak(ID_Pakan, Nama_Pakan, Berat_Pakan, Jenis_Pakan, Harga_Pakan, Stok_Pakan) VALUES(?,?,?,?,?,?);");
             PS.setString(1, ID);
             PS.setString(2, NM);
             PS.setString(3, BT);
             PS.setString(4, JS);
             PS.setString(5, HG);
             PS.setString(6, ST);
             PS.executeUpdate();
         }
    }

private void UpdateData() throws SQLException {
    Connection cnn = buatkoneks();
    if (cnn != null && !cnn.isClosed()) {
        try (PreparedStatement PS = cnn.prepareStatement("UPDATE pakan_ternak SET Nama_Pakan=?, Berat_Pakan=?, Jenis_Pakan=?, Harga_Pakan=?, Stok_Pakan=?,WHERE ID_Pakan=?;")) {
            PS.setString(1, txtNama.getText());
            PS.setString(2, txtBerat.getText());
            PS.setString(3, txtJenis.getText());
            PS.setString(4, txtHarga.getText());
            PS.setString(5, txtStok.getText());
            PS.executeUpdate();
        } finally {
            cnn.close();
        }
    }
}

    private void destroyData() throws SQLException {
        Connection cnn = buatkoneks();
        if(!cnn.isClosed()){
            cnn.isClosed();
            PreparedStatement PS = cnn.prepareStatement("DELETE FROM pakan_ternak WHERE ID_Pakan=?;");
            PS.setString(1, txtID.getText());
            PS.executeUpdate();
            cnn.close();
        }
    }
    private void kosongkanform(){
        txtID.setText("");
        txtNama.setText("");
        txtBerat.setText("");
        txtJenis.setText("");
        txtHarga.setText("");
        txtStok.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPakan = new javax.swing.JTable();
        txtNama = new javax.swing.JTextField();
        txtBerat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtJenis = new javax.swing.JTextField();
        txtJeneis = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBaru = new javax.swing.JButton();
        btnTutupForm = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        Foto = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sistem Input Pakan Ternak");

        tblPakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pakan", "Nama Pakan", "Berat Pakan", "Jenis Pakan", "Harga Pakan", "Stok Pakan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPakanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPakan);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel3.setText("Berat Pakan");

        txtJeneis.setText("Jenis Pakan");

        jLabel5.setText("Harga pakan");

        jLabel6.setText("Stok Pakan");

        btnBaru.setText("Baru");
        btnBaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaruMouseClicked(evt);
            }
        });

        btnTutupForm.setText("TutupForm");
        btnTutupForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupFormActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        Foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FotoMouseClicked(evt);
            }
        });

        jLabel8.setText("Nama Pakan");

        jLabel2.setText("ID Pakan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUbah)
                        .addGap(36, 36, 36)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTutupForm))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtJeneis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtStok, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                            .addComponent(txtHarga)
                                            .addComponent(txtJenis)
                                            .addComponent(txtBerat)
                                            .addComponent(txtNama)
                                            .addComponent(txtID))
                                        .addGap(18, 18, 18)
                                        .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJeneis))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah)
                    .addComponent(btnBaru)
                    .addComponent(btnTutupForm))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTutupFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupFormActionPerformed
        if(btnTutupForm.getText().equals("TutupForm")){
            dispose();
        }else{
            btnTutupForm.setText("TutupForm");
            btnBaru.setText("Baru");
        }
    }//GEN-LAST:event_btnTutupFormActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if(btnBaru.getText().equals("Baru")){
            btnBaru.setText("Simpan");
            btnTutupForm.setText("Batal");
            kosongkanform();
            tblPakan.setEnabled(false);
        }else{
            btnBaru.setText("Baru");
            btnTutupForm.setText("TutupForm");
            tblPakan.setEnabled(true);
            try {
                StoreData();
                List_All();
            } catch (SQLException ex) {
                Logger.getLogger(Jform.class.getName()).log(Level.SEVERE, null, ex);
            }
        }                     
    }//GEN-LAST:event_btnUbahActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void tblPakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPakanMouseClicked
        txtID.setText( tblPakan.getValueAt( tblPakan.getSelectedRow(),0 ).toString() );
        txtNama.setText( tblPakan.getValueAt( tblPakan.getSelectedRow(), 1).toString() );
        txtBerat.setText( tblPakan.getValueAt(tblPakan.getSelectedRow(), 2).toString() );
        txtJenis.setText( tblPakan.getValueAt(tblPakan.getSelectedRow(), 3).toString() );
        txtHarga.setText( tblPakan.getValueAt(tblPakan.getSelectedRow(), 4).toString() );
        txtStok.setText( tblPakan.getValueAt(tblPakan.getSelectedRow(), 5).toString() );

    }//GEN-LAST:event_tblPakanMouseClicked

    private void FotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FotoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FotoMouseClicked

    private void btnBaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaruMouseClicked
              if(btnBaru.getText().equals("Baru")){
            btnBaru.setText("Simpan");
            btnTutupForm.setText("Batal");
            kosongkanform();
            tblPakan.setEnabled(false);
        }else{
            btnBaru.setText("Baru");
            btnTutupForm.setText("TutupForm");
            tblPakan.setEnabled(true);
            try {
                StoreData();
                List_All();
            } catch (SQLException ex) {
                Logger.getLogger(Jform.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBaruMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
                int jwb = JOptionPane.showOptionDialog(
            this, "Yakin Menghapus Data?" + txtID.getText() + "?",
            "Hapus Data",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null, 
            null,
            null);

    if (jwb == JOptionPane.YES_OPTION) {
        try {
            destroyData();
            List_All();
            kosongkanform();
        } catch (SQLException ex) {
            Logger.getLogger(Jform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            Logger.getLogger(Jform.class.getName()).log(Level.WARNING, "Invalid ID format", ex);
        }
    }
    }//GEN-LAST:event_btnHapusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Jform().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Jform.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTutupForm;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPakan;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JLabel txtJeneis;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}

